"""The contract of gemma's paged causal attention kernel (gemma_attn.py),
verbatim sparkle's own gate `tests/test_gemma_attention_gpu.py` with the
imports pointed here. Two-sided:

1. Invariance, BITWISE. A row's output bytes do not depend on how the
   engine computed it. Every row of a 1600-position sequence per kind
   is computed (a) in one whole call, (b) in chunks at the splits
   {700 | 1025 | 512+1024 | 1536+1 | 1536+4}, (c) one row at a time at
   its own kv_len (decode), (d) in 4-row calls (verify), (e) in 1-,
   2-, 3-row calls (eager verify); and under n = 2 sequences in one
   launch. All equal to (a), bytes. The same for the last 64 rows at
   kv 32k and 128k. There is no tolerance and none may be introduced.
2. Correctness, within bf16 rounding of an fp32 reference: on every
   arm the kernel's rel-L2 distance from `reference_rows` is at most
   twice the wheel's own distance (+1e-6), the bound the M-invariant
   linear holds. The wheel (FlashInfer's paged prefill on the engine's
   exact plan) is the comparator, not the contract.

Plus determinism over 8 calls, CUDA-graph capture and replay at rows
1 and 4 with the metadata buffers rewritten between replays (the
served decode and verify shape: `kv_indices` a fixed buffer longer
than the gather, so the split path launches its max block count), and
no torch attention / matmul / softmax / compile on the path.

Synthetic tensors, no checkpoint, no service conflict.

Do not edit this file; a candidate that needs it changed is wrong.
"""

import pytest
import torch

gpu = pytest.mark.gpu

PAGE = 16
HEADS = 16
WINDOW = 1024
KINDS = {
    'sliding': dict(kv_heads=8, head_dim=256, window_left=WINDOW - 1),
    'global': dict(kv_heads=1, head_dim=512, window_left=-1),
}
SCALE = 0.3
L = 1600
LONG_CONTEXTS = (32768, 131072)
LONG_TAIL = 64
SPLITS = {
    '700': [700, L],
    '1025': [1025, L],
    '512+1024': [512, 1536, L],
    '1536+1': [1536, 1537, L],
    '1536+4': [1536, 1540, L],
}


@pytest.fixture(autouse=True)
def _cuda():
  if not torch.cuda.is_available():
    pytest.skip('needs CUDA')


# --- seeded sequences on a paged cache ---------------------------------


class _Seq:

  def __init__(self, total, keep_from, q_from, q_all, table):
    assert keep_from % PAGE == 0
    self.total = total
    self.keep_from = keep_from
    self.q_from = q_from
    self.q_all = q_all
    self.table = table

  def q(self, start, end):
    assert start >= self.q_from and end <= self.total, (start, end)
    return self.q_all[start - self.q_from:end - self.q_from]


class _Cache:
  """Several sequences on one paged bf16 cache, physical pages a random
  permutation so every call's `kv_indices` is a real gather. `meta`
  builds one launch's metadata for `(seq_index, rows, end)` calls —
  the last `rows` positions up to `end` — in the engine's shape plus
  `pos_base`."""

  def __init__(self, kind, pages, seqs):
    self.kind = kind
    self.g = KINDS[kind]
    self.pages = pages
    self.seqs = seqs

  def gather_range(self, si, rows, end):
    s = self.seqs[si]
    first = max(0, end - rows - WINDOW) // PAGE if self.kind == 'sliding' else 0
    assert first * PAGE >= s.keep_from, (first, s.keep_from)
    used = (end + PAGE - 1) // PAGE
    return first, used, end - (used - 1) * PAGE

  def meta(self, calls):
    qo, kvp, idx, last, base = [0], [0], [], [], []
    for si, rows, end in calls:
      first, used, last_len = self.gather_range(si, rows, end)
      qo.append(qo[-1] + rows)
      idx.append(self.seqs[si].table[first:used])
      kvp.append(kvp[-1] + used - first)
      last.append(last_len)
      base.append(first * PAGE)
    i32 = lambda x: torch.tensor(x, dtype=torch.int32, device='cuda'
                                )  # noqa: E731
    return (i32(qo), i32(kvp), torch.cat(idx).to(torch.int32), i32(last),
            i32(base))

  def q(self, calls):
    return torch.cat(
        [self.seqs[si].q(end - rows, end) for si, rows, end in calls])

  def dense_kv(self, si, start, end):
    s = self.seqs[si]
    pos = torch.arange(start, end, device='cuda')
    phys = s.table[pos // PAGE].long()
    slot = pos % PAGE
    return self.pages[phys, 0, slot], self.pages[phys, 1, slot]


def make_cache(kind, seed, specs):
  g = KINDS[kind]
  gen = torch.Generator(device='cuda').manual_seed(seed * 7919 + len(specs))
  specs = [s if len(s) == 3 else (s[0], s[1], s[1]) for s in specs]
  n_pages = [(t + PAGE - 1) // PAGE - k // PAGE for t, k, _ in specs]
  n_phys = sum(n_pages)
  perm = torch.randperm(n_phys, device='cuda', generator=gen).to(torch.int32)
  pages = (torch.randn(n_phys, 2, PAGE, g['kv_heads'], g['head_dim'],
                       device='cuda', generator=gen) * SCALE).bfloat16()
  seqs = []
  off = 0
  for (total, keep_from, q_from), n in zip(specs, n_pages):
    q_all = (torch.randn(total - q_from, HEADS, g['head_dim'], device='cuda',
                         generator=gen) * SCALE).bfloat16()
    table = torch.full(((total + PAGE - 1) // PAGE,), -1, dtype=torch.int32,
                       device='cuda')
    table[keep_from // PAGE:] = perm[off:off + n]
    off += n
    seqs.append(_Seq(total, keep_from, q_from, q_all, table))
  return _Cache(kind, pages, seqs)


# --- the fp32 reference and the wheel ----------------------------------


def reference_rows(cache, si, start, end):
  g = cache.g
  nkv, d, wl = g['kv_heads'], g['head_dim'], g['window_left']
  group = HEADS // nkv
  lo = 0 if wl < 0 else max(0, start - wl)
  k, v = cache.dense_kv(si, lo, end)
  k, v = k.float(), v.float()
  q = cache.seqs[si].q(start, end).float()
  R = end - start
  s = torch.einsum('rhgd,lhd->rhgl', q.view(R, nkv, group, d), k)
  pos = torch.arange(start, end, device='cuda')[:, None]
  key = torch.arange(lo, end, device='cuda')[None, :]
  allowed = key <= pos
  if wl >= 0:
    allowed &= key >= pos - wl
  s = s.masked_fill(~allowed[:, None, None, :], float('-inf'))
  p = torch.softmax(s, dim=-1)
  o = torch.einsum('rhgl,lhd->rhgd', p, v)
  return o.reshape(R, HEADS, d).to(torch.bfloat16)


_WHEEL = {}


def wheel_rows(cache, calls):
  from reference import _new_wrapper  # noqa: PLC0415
  if 'w' not in _WHEEL:
    _WHEEL['w'] = _new_wrapper()
  wr = _WHEEL['w']
  g = cache.g
  qo, kvp, idx, last, _ = cache.meta(calls)
  wr.plan(qo, kvp, idx, last, HEADS, g['kv_heads'], g['head_dim'], PAGE,
          causal=True, sm_scale=1.0, window_left=g['window_left'],
          q_data_type=torch.bfloat16, kv_data_type=torch.bfloat16)
  return wr.run(cache.q(calls), cache.pages)


# --- the arms ----------------------------------------------------------


def _call(cache, calls):
  from gemma_attn import gemma_attention  # noqa: PLC0415
  q = cache.q(calls)
  meta = cache.meta(calls)
  out = torch.empty_like(q)
  gemma_attention(q, cache.pages, *meta, cache.g['window_left'], out)
  torch.cuda.synchronize()
  return out


def _assert_bitwise(out, ref, label):
  if torch.equal(out, ref):
    return
  diff = out != ref
  rows = torch.nonzero(diff.flatten(1).any(1)).flatten().tolist()
  raise AssertionError(
      f'{label}: {int(diff.sum())} elements differ in {len(rows)} rows '
      f'(first rows {rows[:8]}; max |delta| '
      f'{(out.float() - ref.float()).abs().max().item():.3e})')


def _assert_near_fp32(cache, out, si, start, end, label):
  ref = reference_rows(cache, si, start, end).float()
  wheel = wheel_rows(cache, [(si, end - start, end)]).float()
  rel = ((out.float() - ref).norm() / ref.norm()).item()
  rel_w = ((wheel - ref).norm() / ref.norm()).item()
  assert rel <= 2.0 * rel_w + 1e-6, (
      f'{label}: rel-L2 vs fp32 {rel:.3e}, the wheel {rel_w:.3e}')


@pytest.fixture(scope='module', params=list(KINDS))
def kind(request):
  return request.param


@pytest.fixture(scope='module')
def cache(kind):
  if not torch.cuda.is_available():
    pytest.skip('needs CUDA')
  return make_cache(kind, 0, [(L, 0), (L, 0)])


@pytest.fixture(scope='module')
def whole(cache):
  return _call(cache, [(0, L, L)])


@gpu
def test_whole_call_near_fp32(cache, whole):
  _assert_near_fp32(cache, whole, 0, 0, L, 'whole')


@gpu
@pytest.mark.parametrize('name', list(SPLITS))
def test_chunked_equals_whole(cache, whole, name):
  start = 0
  for end in SPLITS[name]:
    out = _call(cache, [(0, end - start, end)])
    _assert_bitwise(out, whole[start:end],
                    f'split {name} chunk [{start}, {end})')
    _assert_near_fp32(cache, out, 0, start, end, f'split {name}')
    start = end


@gpu
@pytest.mark.parametrize('width', [1, 4])
def test_fixed_width_calls_equal_whole(cache, whole, width):
  """width 1 is the decode shape, 4 the verify shape; every row of the
  sequence at its own kv_len."""
  for start in range(0, L, width):
    end = min(start + width, L)
    out = _call(cache, [(0, end - start, end)])
    _assert_bitwise(out, whole[start:end], f'{width}-row call at {start}')


@gpu
def test_eager_verify_widths_equal_whole(cache, whole):
  start = 0
  i = 0
  while start < L:
    width = 1 + i % 3
    end = min(start + width, L)
    out = _call(cache, [(0, end - start, end)])
    _assert_bitwise(out, whole[start:end], f'{width}-row call at {start}')
    start = end
    i += 1


@gpu
@pytest.mark.parametrize('rows', [1, 4, 700])
def test_two_sequences_one_launch(cache, whole, rows):
  """n = 2: each sequence's rows equal their n = 1 bytes. The second
  sequence is at a different length so the gathers differ."""
  end1 = L - 300
  single1 = _call(cache, [(1, rows, end1)])
  out = _call(cache, [(0, rows, L), (1, rows, end1)])
  _assert_bitwise(out[:rows], whole[L - rows:], f'n=2 seq 0, {rows} rows')
  _assert_bitwise(out[rows:], single1, f'n=2 seq 1, {rows} rows')
  _assert_near_fp32(cache, out[rows:], 1, end1 - rows, end1, 'n=2 seq 1')


@gpu
@pytest.mark.parametrize('ctx', LONG_CONTEXTS)
def test_long_context_tail(kind, ctx):
  """The last 64 rows at a long context: as a 4096-row chunk's tail, as
  one 64-row call, one row at a time, in 4-row calls — all equal, and
  within bf16 rounding of fp32."""
  keep = 0 if kind == 'global' else (ctx - 4096 - WINDOW - 16) // 16 * 16
  c = make_cache(kind, 3, [(ctx, keep, ctx - 4096)])
  chunk = _call(c, [(0, 4096, ctx)])[-LONG_TAIL:]
  start = ctx - LONG_TAIL
  _assert_near_fp32(c, chunk, 0, start, ctx, f'{ctx} chunk tail')
  tail = _call(c, [(0, LONG_TAIL, ctx)])
  _assert_bitwise(tail, chunk, f'{ctx} 64-row call vs chunk tail')
  for w in (1, 4):
    for s in range(start, ctx, w):
      out = _call(c, [(0, w, s + w)])
      _assert_bitwise(out, chunk[s - start:s - start + w],
                      f'{ctx} {w}-row call at {s} vs chunk tail')
  del c
  torch.cuda.empty_cache()


@gpu
def test_deterministic_over_calls(cache):
  first = _call(cache, [(0, 1025, 1025)])
  for i in range(7):
    _assert_bitwise(_call(cache, [(0, 1025, 1025)]), first,
                    f'call {i + 2} vs call 1')


@gpu
@pytest.mark.parametrize('rows', [1, 4])
def test_cuda_graph_capture_and_replay(cache, whole, rows):
  """Decode and verify replay under CUDA graphs with the metadata
  buffers rewritten between replays: no host sync, no data-dependent
  host work, the metadata read on device. `kv_indices` is a fixed
  buffer longer than the gather, the served shape."""
  from gemma_attn import gemma_attention  # noqa: PLC0415
  calls = [(0, rows, L - 200)]
  q = cache.q(calls).clone()
  qo, kvp, idx, last, base = cache.meta(calls)
  idx_buf = torch.zeros(4096, dtype=torch.int32, device='cuda')
  idx_buf[:idx.numel()] = idx
  out = torch.empty_like(q)
  wl = cache.g['window_left']
  stream = torch.cuda.Stream()
  with torch.cuda.stream(stream):
    for _ in range(3):
      gemma_attention(q, cache.pages, qo, kvp, idx_buf, last, base, wl, out)
  torch.cuda.current_stream().wait_stream(stream)
  graph = torch.cuda.CUDAGraph()
  with torch.cuda.graph(graph):
    gemma_attention(q, cache.pages, qo, kvp, idx_buf, last, base, wl, out)
  out.zero_()
  graph.replay()
  torch.cuda.synchronize()
  _assert_bitwise(out, whole[L - 200 - rows:L - 200], 'graph replay')
  calls2 = [(0, rows, L)]
  qo2, kvp2, idx2, last2, base2 = cache.meta(calls2)
  q.copy_(cache.q(calls2))
  kvp.copy_(kvp2)
  idx_buf[:idx2.numel()] = idx2
  last.copy_(last2)
  base.copy_(base2)
  graph.replay()
  torch.cuda.synchronize()
  _assert_bitwise(out, whole[L - rows:], 'graph replay, rewritten metadata')


@gpu
def test_no_torch_attention_on_the_path(monkeypatch, cache):
  import torch.nn.functional as F  # noqa: PLC0415

  def boom(*a, **k):
    raise AssertionError('torch op on the main path')

  for mod, name in ((torch, 'matmul'), (torch, 'bmm'), (torch, 'einsum'),
                    (F, 'scaled_dot_product_attention'), (torch, 'compile'),
                    (torch, 'softmax')):
    monkeypatch.setattr(mod, name, boom)
  _call(cache, [(0, 4, L)])


# --- the image block mask, task next.121 --------------------------------
#
# The sliding kind's one custom mask: inside an image's absolute span
# `[lo, hi)` keys are bidirectional, under the window; everywhere else
# the row is plain causal. It enters the kernel as per-sequence span
# metadata — `span_indptr` int32 [n + 1], `span_bounds` int32 [S, 2],
# absolute — and drops into `ok` without touching the fold, so (a) a
# text row's bytes do not depend on whether a span rode in its launch,
# (b) chunking on a grid that never straddles a span is bitwise
# invariant exactly as the text path is, and (c) a launch with empty
# span tensors is bit-for-bit the launch without them. The correctness
# comparator is the wheel under its packed custom mask (the path this
# replaces), the predicate `image_block_mask_bool` documents.

SPANS = {
    'one': ((300, 580),),
    'two': ((100, 380), (1200, 1480)),
}
# No chunk boundary falls inside a span (the engine's no-straddle grid,
# `test_gemma_admission_plans_a_no_straddle_chunk_grid`); the tails are
# the step shapes after an image.
SPAN_SPLITS = {
    'one': [580, 1024, L],
    'two': [380, 1200, 1480, 1481, 1485, L],
}


def _span_tensors(spans_per_seq):
  indptr, bounds = [0], []
  for spans in spans_per_seq:
    bounds.extend(spans)
    indptr.append(len(bounds))
  i32 = lambda x: torch.tensor(x, dtype=torch.int32, device='cuda'
                              )  # noqa: E731
  return i32(indptr), i32(bounds).reshape(-1, 2)


def _call_spanned(cache, calls, spans_per_seq):
  from gemma_attn import gemma_attention  # noqa: PLC0415
  q = cache.q(calls)
  meta = cache.meta(calls)
  out = torch.empty_like(q)
  si, sb = _span_tensors(spans_per_seq)
  gemma_attention(q, cache.pages, *meta, cache.g['window_left'], out,
                  span_indptr=si, span_bounds=sb)
  torch.cuda.synchronize()
  return out


def _spanned_allowed(start, end, lo, spans):
  """The predicate: AND(window, OR(causal, same span)), window the
  outer clause on both disjuncts (DOC#VISION-GEMMA)."""
  pos = torch.arange(start, end, device='cuda')[:, None]
  key = torch.arange(lo, end, device='cuda')[None, :]
  block = torch.zeros_like(pos, dtype=torch.bool) | torch.zeros_like(
      key, dtype=torch.bool)
  for a, b in spans:
    block |= (pos >= a) & (pos < b) & (key >= a) & (key < b)
  return ((key <= pos) | block) & (key >= pos - (WINDOW - 1))


def spanned_reference_rows(cache, si, start, end, spans):
  g = cache.g
  nkv, d = g['kv_heads'], g['head_dim']
  group = HEADS // nkv
  lo = max(0, start - (WINDOW - 1))
  k, v = cache.dense_kv(si, lo, end)
  q = cache.seqs[si].q(start, end).float()
  R = end - start
  s = torch.einsum('rhgd,lhd->rhgl', q.view(R, nkv, group, d), k.float())
  allowed = _spanned_allowed(start, end, lo, spans)
  s = s.masked_fill(~allowed[:, None, None, :], float('-inf'))
  o = torch.einsum('rhgl,lhd->rhgd', torch.softmax(s, dim=-1), v.float())
  return o.reshape(R, HEADS, d).to(torch.bfloat16)


def spanned_wheel_rows(cache, si, start, end, spans):
  """The wheel on the engine's exact masked plan: `causal=False`, no
  `window_left`, the predicate bit-packed little-endian over the
  gathered page window (the retired `image_block_mask` form)."""
  from reference import _new_wrapper  # noqa: PLC0415
  if 'w' not in _WHEEL:
    _WHEEL['w'] = _new_wrapper()
  wr = _WHEEL['w']
  g = cache.g
  calls = [(si, end - start, end)]
  qo, kvp, idx, last, base = cache.meta(calls)
  origin = int(base[0])
  allowed = _spanned_allowed(start, end, origin, spans).reshape(-1)
  pad = (-allowed.numel()) % 8
  if pad:
    allowed = torch.cat(
        [allowed, torch.zeros(pad, dtype=torch.bool, device='cuda')])
  bits = allowed.reshape(-1, 8).to(torch.uint8)
  packed = (bits << torch.arange(8, device='cuda', dtype=torch.uint8)).sum(
      1, dtype=torch.uint8)
  wr.plan(qo, kvp, idx, last, HEADS, g['kv_heads'], g['head_dim'], PAGE,
          causal=False, sm_scale=1.0, q_data_type=torch.bfloat16,
          kv_data_type=torch.bfloat16, packed_custom_mask=packed)
  return wr.run(cache.q(calls), cache.pages)


def _assert_spanned_near_fp32(cache, out, si, start, end, spans, label):
  ref = spanned_reference_rows(cache, si, start, end, spans).float()
  wheel = spanned_wheel_rows(cache, si, start, end, spans).float()
  rel = ((out.float() - ref).norm() / ref.norm()).item()
  rel_w = ((wheel - ref).norm() / ref.norm()).item()
  assert rel <= 2.0 * rel_w + 1e-6, (
      f'{label}: rel-L2 vs fp32 {rel:.3e}, the wheel {rel_w:.3e}')


@pytest.fixture(scope='module')
def sliding_cache(kind, cache):
  if kind != 'sliding':
    pytest.skip('the image block mask reaches the sliding kind only')
  return cache


@gpu
@pytest.mark.parametrize('name', list(SPANS))
def test_spanned_whole_near_fp32(sliding_cache, name):
  spans = SPANS[name]
  out = _call_spanned(sliding_cache, [(0, L, L)], [spans])
  _assert_spanned_near_fp32(sliding_cache, out, 0, 0, L, spans,
                            f'spans {name} whole')
  # The block is load-bearing: the spanned rows differ from causal.
  ref = spanned_reference_rows(sliding_cache, 0, 0, L, spans).float()
  ref0 = reference_rows(sliding_cache, 0, 0, L).float()
  lo, hi = spans[0]
  gap = ((ref[lo:hi] - ref0[lo:hi]).norm() / ref[lo:hi].norm()).item()
  assert gap > 1e-3, f'spans {name}: image block not load-bearing: {gap:.3e}'


@gpu
@pytest.mark.parametrize('name', list(SPANS))
def test_spanned_text_rows_equal_unspanned(sliding_cache, whole, name):
  """Rows outside every span — before, between and after the images,
  including the rows that attend image keys causally through the
  window — are bit-equal to the launch with no spans at all."""
  spans = SPANS[name]
  out = _call_spanned(sliding_cache, [(0, L, L)], [spans])
  text = torch.ones(L, dtype=torch.bool, device='cuda')
  for lo, hi in spans:
    text[lo:hi] = False
  _assert_bitwise(out[text], whole[text], f'spans {name} text rows')
  assert not torch.equal(out[~text], whole[~text]), 'spans must bite'


@gpu
@pytest.mark.parametrize('name', list(SPANS))
def test_spanned_chunked_equals_whole(sliding_cache, name):
  """Chunking on the no-straddle grid, every chunk launched with the
  whole prompt's spans (the engine hands every chunk
  `step_ctx.image_spans`), equals the whole spanned call bitwise; the
  1- and 4-row tails after an image are launched with NO spans, as
  decode and verify are, and equal it too."""
  spans = SPANS[name]
  whole_s = _call_spanned(sliding_cache, [(0, L, L)], [spans])
  start = 0
  for end in SPAN_SPLITS[name]:
    rows = end - start
    if rows <= 4:
      out = _call(sliding_cache, [(0, rows, end)])
    else:
      out = _call_spanned(sliding_cache, [(0, rows, end)], [spans])
    _assert_bitwise(out, whole_s[start:end],
                    f'spans {name} chunk [{start}, {end})')
    if rows > 4:
      _assert_spanned_near_fp32(sliding_cache, out, 0, start, end, spans,
                                f'spans {name} chunk [{start}, {end})')
    start = end


@gpu
def test_spanned_second_sequence_in_one_launch(sliding_cache, whole):
  """n = 2 with spans on the second sequence only: the first keeps its
  n = 1 bytes, the second its own spanned n = 1 bytes."""
  spans = SPANS['one']
  end1 = L - 300
  single1 = _call_spanned(sliding_cache, [(1, end1, end1)], [spans])
  out = _call_spanned(sliding_cache, [(0, L, L), (1, end1, end1)], [(), spans])
  _assert_bitwise(out[:L], whole, 'n=2 seq 0 unspanned')
  _assert_bitwise(out[L:], single1, 'n=2 seq 1 spanned')


@gpu
def test_empty_spans_equal_default(cache, whole):
  """Both kinds: explicit empty span tensors are the default launch,
  bytes — the one configuration class decode and verify replay."""
  out = _call_spanned(cache, [(0, L, L)], [()])
  _assert_bitwise(out, whole, 'empty spans, whole')
  out = _call_spanned(cache, [(0, 4, L)], [()])
  _assert_bitwise(out, whole[L - 4:], 'empty spans, 4 rows')
