"""The contract, two-sided:

1. Invariance, BITWISE. A row's output bytes do not depend on how the
   engine computed it. Every row of a 1600-position sequence per kind
   is computed (a) in one whole call, (b) in chunks at the splits
   {700 | 1025 | 512+1024 | 1536+1 | 1536+4}, (c) one row at a time at
   its own kv_len (decode), (d) in 4-row calls (verify), (e) in 1-,
   2-, 3-row calls (eager verify); and under n = 2 sequences in one
   launch. All equal to (a), bytes. The same for the last 64 rows at
   kv 32k and 128k. There is no tolerance and none may be introduced.
2. Correctness, within bf16 rounding of the fp32 reference: on every
   arm the candidate's rel-L2 distance from `reference_rows` is at most
   twice the wheel's own distance (+1e-6), the bound sparkle holds its
   M-invariant linear to. The wheel is the comparator, not the
   contract: its bytes are the thing being left.

Plus determinism over 8 calls, CUDA-graph capture and replay at rows
1 and 4 with the metadata buffers rewritten between replays, and no
torch attention / matmul / softmax / compile on the path.

Do not edit this file; a candidate that needs it changed is wrong.
"""

from __future__ import annotations

import pytest
import torch

from data import make_cache
from gemma_attn import gemma_attention
from reference import reference_rows, wheel_attention
from shapes import (HEADS, KINDS, LONG_CONTEXTS, LONG_TAIL, VALIDATE_LEN,
                    WINDOW)

L = VALIDATE_LEN
SPLITS = {
    '700': [700, L],
    '1025': [1025, L],
    '512+1024': [512, 1536, L],
    '1536+1': [1536, 1537, L],
    '1536+4': [1536, 1540, L],
}


def _call(cache, calls, fn=gemma_attention):
  q = cache.q(calls)
  meta = cache.meta(calls)
  out = torch.empty_like(q)
  if fn is wheel_attention:
    wheel_attention(cache, q, meta, out)
  else:
    fn(q, cache.pages, *meta, cache.g['window_left'], out)
  torch.cuda.synchronize()
  return out


def _assert_bitwise(out, ref, label):
  if torch.equal(out, ref):
    return
  diff = out != ref
  rows = torch.nonzero(diff.flatten(1).any(1)).flatten().tolist()
  raise AssertionError(
      f'{label}: {int(diff.sum())} elements differ in {len(rows)} rows '
      f'(first rows {rows[:8]}; max |delta| '
      f'{(out.float() - ref.float()).abs().max().item():.3e})')


def _assert_near_fp32(cache, out, si, start, end, label):
  ref = reference_rows(cache, si, start, end).float()
  wheel = _call(cache, [(si, end - start, end)], wheel_attention).float()
  rel = ((out.float() - ref).norm() / ref.norm()).item()
  rel_w = ((wheel - ref).norm() / ref.norm()).item()
  assert rel <= 2.0 * rel_w + 1e-6, (
      f'{label}: rel-L2 vs fp32 {rel:.3e}, the wheel {rel_w:.3e}')


@pytest.fixture(scope='module', params=list(KINDS))
def kind(request):
  return request.param


@pytest.fixture(scope='module')
def cache(kind):
  return make_cache(kind, 0, [(L, 0), (L, 0)])


@pytest.fixture(scope='module')
def whole(cache):
  return _call(cache, [(0, L, L)])


def test_whole_call_near_fp32(cache, whole):
  _assert_near_fp32(cache, whole, 0, 0, L, 'whole')


@pytest.mark.parametrize('name', list(SPLITS))
def test_chunked_equals_whole(cache, whole, name):
  start = 0
  for end in SPLITS[name]:
    out = _call(cache, [(0, end - start, end)])
    _assert_bitwise(out, whole[start:end], f'split {name} chunk [{start}, {end})')
    _assert_near_fp32(cache, out, 0, start, end, f'split {name}')
    start = end


@pytest.mark.parametrize('width', [1, 4])
def test_fixed_width_calls_equal_whole(cache, whole, width):
  """width 1 is the decode shape, 4 the verify shape; every row of the
  sequence at its own kv_len."""
  for start in range(0, L, width):
    end = min(start + width, L)
    out = _call(cache, [(0, end - start, end)])
    _assert_bitwise(out, whole[start:end], f'{width}-row call at {start}')


def test_eager_verify_widths_equal_whole(cache, whole):
  start = 0
  i = 0
  while start < L:
    width = 1 + i % 3
    end = min(start + width, L)
    out = _call(cache, [(0, end - start, end)])
    _assert_bitwise(out, whole[start:end], f'{width}-row call at {start}')
    start = end
    i += 1


@pytest.mark.parametrize('rows', [1, 4, 700])
def test_two_sequences_one_launch(cache, whole, rows):
  """n = 2: each sequence's rows equal their n = 1 bytes. The second
  sequence is at a different length so the gathers differ."""
  end1 = L - 300
  single1 = _call(cache, [(1, rows, end1)])
  out = _call(cache, [(0, rows, L), (1, rows, end1)])
  _assert_bitwise(out[:rows], whole[L - rows:], f'n=2 seq 0, {rows} rows')
  _assert_bitwise(out[rows:], single1, f'n=2 seq 1, {rows} rows')
  _assert_near_fp32(cache, out[rows:], 1, end1 - rows, end1, f'n=2 seq 1')


@pytest.mark.parametrize('ctx', LONG_CONTEXTS)
def test_long_context_tail(kind, ctx):
  """The last 64 rows at a long context: as a 4096-row chunk's tail, as
  one 64-row call, one row at a time, in 4-row calls — all equal, and
  within bf16 rounding of fp32."""
  keep = 0 if kind == 'global' else (ctx - 4096 - WINDOW - 16) // 16 * 16
  c = make_cache(kind, 3, [(ctx, keep, ctx - 4096)])
  chunk = _call(c, [(0, 4096, ctx)])[-LONG_TAIL:]
  start = ctx - LONG_TAIL
  _assert_near_fp32(c, chunk, 0, start, ctx, f'{ctx} chunk tail')
  tail = _call(c, [(0, LONG_TAIL, ctx)])
  _assert_bitwise(tail, chunk, f'{ctx} 64-row call vs chunk tail')
  for w in (1, 4):
    for s in range(start, ctx, w):
      out = _call(c, [(0, w, s + w)])
      _assert_bitwise(out, chunk[s - start:s - start + w],
                      f'{ctx} {w}-row call at {s} vs chunk tail')
  del c
  torch.cuda.empty_cache()


def test_deterministic_over_calls(cache):
  first = _call(cache, [(0, 1025, 1025)])
  for i in range(7):
    _assert_bitwise(_call(cache, [(0, 1025, 1025)]), first,
                    f'call {i + 2} vs call 1')


@pytest.mark.parametrize('rows', [1, 4])
def test_cuda_graph_capture_and_replay(cache, whole, rows):
  """Decode and verify replay under CUDA graphs with the metadata
  buffers rewritten between replays: no host sync, no data-dependent
  host work, the metadata read on device."""
  calls = [(0, rows, L - 200)]
  q = cache.q(calls).clone()
  qo, kvp, idx, last, base = cache.meta(calls)
  idx_buf = torch.zeros(4096, dtype=torch.int32, device='cuda')
  idx_buf[:idx.numel()] = idx
  out = torch.empty_like(q)
  wl = cache.g['window_left']
  stream = torch.cuda.Stream()
  with torch.cuda.stream(stream):
    for _ in range(3):
      gemma_attention(q, cache.pages, qo, kvp, idx_buf, last, base, wl, out)
  torch.cuda.current_stream().wait_stream(stream)
  graph = torch.cuda.CUDAGraph()
  with torch.cuda.graph(graph):
    gemma_attention(q, cache.pages, qo, kvp, idx_buf, last, base, wl, out)
  out.zero_()
  graph.replay()
  torch.cuda.synchronize()
  _assert_bitwise(out, whole[L - 200 - rows:L - 200], 'graph replay')
  # the same graph at the sequence's end: new q, new metadata
  calls2 = [(0, rows, L)]
  qo2, kvp2, idx2, last2, base2 = cache.meta(calls2)
  q.copy_(cache.q(calls2))
  kvp.copy_(kvp2)
  idx_buf[:idx2.numel()] = idx2
  last.copy_(last2)
  base.copy_(base2)
  graph.replay()
  torch.cuda.synchronize()
  _assert_bitwise(out, whole[L - rows:], 'graph replay, rewritten metadata')


def test_no_torch_attention_on_the_path(monkeypatch, cache):
  import torch.nn.functional as F  # noqa: PLC0415

  def boom(*a, **k):
    raise AssertionError('torch op on the main path')

  for mod, name in ((torch, 'matmul'), (torch, 'bmm'), (torch, 'einsum'),
                    (F, 'scaled_dot_product_attention'), (torch, 'compile'),
                    (torch, 'softmax')):
    monkeypatch.setattr(mod, name, boom)
  _call(cache, [(0, 4, L)])
