"""The contract: `linear` in mconst_thin.py is BITWISE equal to the
reference kernel's output on every shape, at every M and under both
tile names. There is no tolerance and none may be introduced; one
differing element fails. Do not edit this file.
"""
import pytest
import torch

import mconst_thin
import reference
from shapes import SHAPES


def _make(seed, N, K, M):
  g = torch.Generator(device='cuda').manual_seed(seed)
  w = (torch.randn(N, K, device='cuda', generator=g) * 0.02).bfloat16()
  x = (torch.randn(M, K, device='cuda', generator=g) * 0.5).bfloat16()
  return x, w


def _assert_bitwise(a, b, label):
  assert a.dtype == b.dtype and a.shape == b.shape, label
  if torch.equal(a, b):
    return
  d = a != b
  raise AssertionError(f'{label}: {int(d.sum())} of {a.numel()} differ '
                       f'(max |delta| {(a.float() - b.float()).abs().max().item():.3e})')


@pytest.mark.parametrize('name', list(SHAPES))
@pytest.mark.parametrize('M', [1, 2, 3, 4, 5, 6, 7, 8, 16, 63, 4096, 8192])
@pytest.mark.parametrize('tile', ['thin', 'wide'])
def test_bitwise(name, M, tile):
  N, K, _ = SHAPES[name]
  if M > 8 and name == 'kv_proj' and tile == 'thin':
    pytest.skip('the thin tile is never launched wide on kv_proj')
  x, w = _make(11 * M + len(name), N, K, M)
  _assert_bitwise(mconst_thin.linear(x, w, tile=tile),
                  reference.linear(x, w, tile=tile), f'{name} M={M} {tile}')


@pytest.mark.parametrize('name', list(SHAPES))
def test_row_invariance(name):
  """A row's bytes do not depend on how many rows share the call."""
  N, K, _ = SHAPES[name]
  x, w = _make(99, N, K, 8)
  full = mconst_thin.linear(x, w, tile='thin')
  for M in (1, 5):
    _assert_bitwise(mconst_thin.linear(x[:M].contiguous(), w, tile='thin'),
                    full[:M], f'{name} rows {M} of 8')


def test_determinism():
  N, K, _ = SHAPES['down_inject']
  x, w = _make(7, N, K, 5)
  first = mconst_thin.linear(x, w, tile='thin')
  for _ in range(8):
    _assert_bitwise(mconst_thin.linear(x, w, tile='thin'), first, 'repeat')


def test_cuda_graph_replay():
  """Decode and verify replay under CUDA graphs: a plain launch, no
  host sync, no data-dependent host work, inputs swapped between
  replays."""
  N, K, _ = SHAPES['down_inject']
  x, w = _make(5, N, K, 5)
  x2, w2 = _make(6, N, K, 5)
  xs, ws = x.clone(), w.clone()
  s = torch.cuda.Stream()
  with torch.cuda.stream(s):
    for _ in range(3):
      mconst_thin.linear(xs, ws, tile='thin')
  torch.cuda.current_stream().wait_stream(s)
  g = torch.cuda.CUDAGraph()
  with torch.cuda.graph(g):
    y = mconst_thin.linear(xs, ws, tile='thin')
  g.replay()
  torch.cuda.synchronize()
  _assert_bitwise(y, reference.linear(x, w, tile='thin'), 'graph 1')
  xs.copy_(x2)
  ws.copy_(w2)
  g.replay()
  torch.cuda.synchronize()
  _assert_bitwise(y, reference.linear(x2, w2, tile='thin'), 'graph 2')


def test_rejects_bad_operands():
  N, K, _ = SHAPES['down_inject']
  x, w = _make(1, N, K, 1)
  with pytest.raises(ValueError):
    mconst_thin.linear(x.float(), w, tile='thin')
  with pytest.raises(ValueError):
    mconst_thin.linear(x, w, tile='nope')
