"""Scaffold a kernel project from a flashinfer-bench definition.

Everything kernel-specific is derived from the definition JSON — the reference
implementation, the stub signature, and the I/O tables in AGENTS.md. Everything
language-specific comes from a profile in assets/lang/. Nothing is hand-transcribed,
because a wrong shape in AGENTS.md misleads the agent for an entire run.
"""

from __future__ import annotations

import json
import re
import shutil
import subprocess
import textwrap
from pathlib import Path

from kopt.agent import BACKENDS

ASSETS = Path(__file__).parent / "assets"
GIT_IDENT = ["-c", "user.email=kopt@localhost", "-c", "user.name=kopt"]

LESSONS = (
    "# Lessons\n\n"
    "Durable cross-experiment findings. Append when a lesson recurs. Remove entries\n"
    "that later turn out to be wrong — a stale lesson blocks a good idea forever.\n"
)

# Language profile -> (flashinfer-bench BuildSpec language, source directory).
# These differ for CuTeDSL: it is Python-JIT so it packs with the triton builder,
# but lives in its own folder so the agent never confuses the two.
BUILD = {
    "triton": ("triton", "triton"),
    "cuda": ("cuda", "cuda"),
    "cutedsl": ("triton", "cutedsl"),
}


def languages() -> list[str]:
    return sorted(p.stem for p in (ASSETS / "lang").glob("*.md"))


def _table(spec: dict, title: str, note: str = "") -> str:
    lines = [f"### {title}{note}", "", "| name | shape | dtype |", "|---|---|---|"]
    for name, s in spec.items():
        shape = s.get("shape")
        shape = "scalar" if not shape else "[" + ", ".join(str(x) for x in shape) + "]"
        lines.append(f"| `{name}` | `{shape}` | {s.get('dtype', '?')} |")
    return "\n".join(lines)


def _kernel_section(defn: dict, source_dir: str, kernel_file: str, baseline_file: str) -> str:
    parts = [
        "## This kernel",
        "",
        f"**Definition:** `{defn['name']}`",
        "",
        defn.get("description", "").strip(),
        "",
        f"**You edit:** `solution/{source_dir}/{kernel_file}` — entry point `kernel`",
        f"**Reference:** `solution/{source_dir}/{baseline_file}` — read for numerical semantics",
        "",
        _table(defn.get("inputs", {}), "Inputs"),
        "",
        _table(
            defn.get("outputs", {}),
            "Outputs",
            " (DPS — pre-allocated and passed in; never allocate these inside the kernel)",
        ),
    ]

    axes = defn.get("axes") or {}
    if axes:
        rows = ["", "### Axes", "", "| axis | kind | detail |", "|---|---|---|"]
        for name, a in axes.items():
            kind = a.get("type", "?")
            detail = (a.get("description") or "").strip()
            if kind == "const":
                fixed = f"always {a.get('value')}"
                detail = f"{fixed} — {detail}" if detail else fixed
            rows.append(f"| `{name}` | {kind} | {detail} |")
        parts.append("\n".join(rows))

    constraints = defn.get("constraints") or []
    if constraints:
        parts.append("\n### Constraints\n\n" + "\n".join(f"- `{c}`" for c in constraints))

    return "\n".join(parts) + "\n"


def _stub(defn: dict) -> str:
    args = list(defn.get("inputs", {})) + list(defn.get("outputs", {}))
    return (
        f'"""Kernel under optimization: {defn["name"]}.\n\n'
        f"{defn.get('description', '').strip()}\n\n"
        "Outputs are destination-passing: write into them, do not allocate.\n"
        '"""\n\n\n'
        f"def kernel({', '.join(args)}):\n"
        '    raise NotImplementedError("implement the fused kernel")\n'
    )


CONFIG = """\
# Generated by `kopt init`. Kernel + backend settings for kbench.

[kernel]
definition = "{definition}"
language = "{language}"      # build toolchain{lang_note}
source_dir = "{source_dir}"
entry_point = "{kernel_file}::kernel"

[remote]
backend = "{backend}"   # local | modal | fal   (override: KBENCH_BACKEND)
gpu = "{gpu}"
gpu_count = 1
timeout_s = 1800

[remote.image]
base = "flashinfer/flashinfer-ci-cu132:latest"
apt = ["git", "wget", "build-essential", "cmake"]
# cupti-python is required for accurate GPU timing; without it the timer falls back
# to CUDA events and over-reports latency by launch overhead (~2-4us per call).
pip = ["huggingface_hub", "cupti-python"]
run = [
  "pip install --force-reinstall --upgrade git+https://github.com/flashinfer-ai/flashinfer-bench.git@main",
]

[remote.image.env]
TORCH_EXTENSIONS_DIR = "/results/torch_ext_cache"
# This image's Triton ships without `triton.backends` entry-point metadata, so default
# discovery finds 0 backends -> "0 active drivers". Force in-tree directory scan.
TRITON_BACKENDS_IN_TREE = "1"

[remote.data]
path = "/data"                    # mount point inside the container (fal: /data/<subdir>)
modal_volume = "flashinfer-trace"
local_path = "~/flashinfer-trace"

[bench]
warmup_runs = 3
iterations = 100
num_trials = 5
profile_baseline = false
"""


# --- agent home -------------------------------------------------------------

AGENT_CONFIG = """
[agent]
kind = "{kind}"   # omp | pi
# pi only: the complete extension set the loop loads (discovery is off). Paths, ~ ok.
extensions = {extensions}
# pi only: tools to disable. Mirrors the omp deny list: no web, no delegation to
# web-capable agents, nothing that would block a headless run.
exclude_tools = ["agy_run", "agy_status", "web_search", "cloxy_fetch", "cloxy_ingest"]
"""


def agent_config_toml(kind: str, extensions: tuple[str, ...]) -> str:
    return AGENT_CONFIG.format(kind=kind, extensions=json.dumps(list(extensions)))


def _for_agent(text: str, kind: str) -> str:
    """Retarget shared prose that names the omp home directory."""
    if kind == "omp":
        return text
    return re.sub(r"\.omp(?![\w-])", ".pi", text.replace(".omp/AGENTS.md", "AGENTS.md"))


def _omp_agent_to_pi_subagent(text: str) -> str:
    """omp `agents/x.md` (name/description/systemPrompt frontmatter) to a pi subagent
    definition: frontmatter for the runner, the system prompt as the body."""
    lines = text.splitlines()
    assert lines and lines[0].strip() == "---", "agent file must start with frontmatter"
    name = description = ""
    prompt: list[str] = []
    in_prompt = False
    end = len(lines)
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            end = i
            break
        if in_prompt:
            if line.startswith("  ") or not line.strip():
                prompt.append(line)
                continue
            in_prompt = False
        if line.startswith("name:"):
            name = line.split(":", 1)[1].strip()
        elif line.startswith("description:"):
            description = line.split(":", 1)[1].strip()
        elif line.startswith("systemPrompt:"):
            in_prompt = True
    body = textwrap.dedent("\n".join(prompt)).strip() + "\n"
    trailing = "\n".join(lines[end + 1:]).strip()
    if trailing:
        body += "\n" + trailing + "\n"
    return (
        "---\n"
        f"label: {name}\n"
        "mode: rpc\n"
        "---\n"
        f"{description}\n\n"
        f"{body}"
    )


def _pi_subagents_section(agents_dir: Path) -> str:
    """Our subagent extension does not advertise definitions to the model; the
    instructions have to name them."""
    rows = []
    for f in sorted(agents_dir.glob("*.md")):
        desc = ""
        for line in f.read_text().splitlines():
            if line.startswith("description:"):
                desc = line.split(":", 1)[1].strip()
                break
        rows.append(f"| `{f.stem}` | {desc} |")
    return (
        "## Subagents\n\n"
        "Delegate with the `subagent` tool: `subagent(agent=\"<name>\", prompt=\"...\")`."
        " Definitions live in `.pi/subagents/`. You are notified when one settles;"
        " do not poll.\n\n"
        "| name | when |\n|---|---|\n" + "\n".join(rows) + "\n"
    )


def _agent_home(project: Path, kind: str, agents_md: str, assets: Path) -> None:
    """Write the agent's project-local instructions, skills and helper agents.

    omp reads `.omp/{AGENTS.md,config.yml,skills,agents}`. pi reads `AGENTS.md` at the
    project root and `.pi/{skills,subagents}`; tool gating is by extension list on the
    command line, so there is no config file.
    """
    if kind not in BACKENDS:
        raise SystemExit(f"unknown agent {kind!r}; have: {', '.join(BACKENDS)}")
    if kind == "omp":
        home = project / ".omp"
        home.mkdir(exist_ok=True)
        (home / "AGENTS.md").write_text(agents_md)
        shutil.copy(ASSETS / "config.yml", home / "config.yml")
        for sub in ("skills", "agents"):
            shutil.copytree(assets / sub, home / sub, dirs_exist_ok=True)
        return

    home = project / ".pi"
    (home / "subagents").mkdir(parents=True, exist_ok=True)
    (project / "AGENTS.md").write_text(
        _for_agent(agents_md, kind).rstrip() + "\n\n" + _pi_subagents_section(assets / "agents")
    )
    shutil.copytree(assets / "skills", home / "skills", dirs_exist_ok=True)
    for skill in (home / "skills").rglob("SKILL.md"):
        skill.write_text(_for_agent(skill.read_text(), kind))
    for agent in (assets / "agents").glob("*.md"):
        (home / "subagents" / agent.name).write_text(_omp_agent_to_pi_subagent(agent.read_text()))


def _git_init(project: Path, ignore: str) -> None:
    """Make the project its own repo.

    AGENTS.md tells the agent to commit after each logged experiment. Without a repo
    here, `git commit` walks up to whatever repo contains the project and commits
    unrelated work — so the scaffold owns its own history.
    """
    if (project / ".git").exists():
        return
    # `/*.log` ignores only the root-level tee target; experiments/exp_N/bench.log is
    # evidence and must be committed.
    (project / ".gitignore").write_text(ignore + ".kopt/\n.kbench/\n__pycache__/\n/*.log\n")
    try:
        for cmd in (["init", "-q"], ["add", "-A"], [*GIT_IDENT, "commit", "-q", "-m", "scaffold"]):
            _run_git(cmd, project)
    except (OSError, subprocess.CalledProcessError) as exc:
        print(f"  warning: could not init git repo ({exc}); agent commits may escape")


def _seed_experiments(project: Path, summary_header: str) -> None:
    """The optimize skill reads both index files on its first step; seed them so a
    fresh run does not open with two failed reads."""
    experiments = project / "experiments"
    experiments.mkdir(exist_ok=True)
    (experiments / "summary.md").write_text(f"# Experiment index\n\n{summary_header}")
    (experiments / "LESSONS.md").write_text(LESSONS)


def _run_git(args: list[str], cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True, text=True)


def _copy_local_repo(source: Path, work: Path) -> None:
    """Snapshot a plain directory into ``work`` as a fresh git repo.

    Used for `[task.repo] path`: small in-tree examples that are not repositories of
    their own. The copy gets one "baseline" commit so kbench provenance, A/B refs, and
    the agent's per-experiment commits work exactly as they do for a clone.
    """
    if not source.is_dir():
        raise SystemExit(f"task.repo.path is not a directory: {source}")
    print(f"  copying {source} -> {work}")
    shutil.copytree(
        source,
        work,
        ignore=shutil.ignore_patterns(".git", "__pycache__", ".pytest_cache", ".DS_Store"),
    )
    for cmd in (["init", "-q", "-b", "main"], ["add", "-A"],
                [*GIT_IDENT, "commit", "-q", "-m", "baseline"]):
        _run_git(cmd, work)


def init_task(
    project: Path,
    taskspec: Path,
    force: bool = False,
    agent: str = "omp",
    extensions: tuple[str, ...] = (),
) -> Path:
    """Create an isolated task project from a short, human-authored brief.

    The target repository is cloned below the project. A first agent turn later reads
    it without modifying it, builds ``harness/``, and tailors the project-local skills.
    """
    import tomllib

    from kbench.config import _load_task

    # `work/` is gitignored, so projects there stay invisible to the framework-integrity
    # checks in `kopt run`; anywhere else inside the checkout would trip them.
    source_checkout = Path(__file__).resolve().parents[1]
    work_root = source_checkout / "work"
    resolved_project = project.resolve()
    under_work = resolved_project != work_root and resolved_project.is_relative_to(work_root)
    if resolved_project.is_relative_to(source_checkout) and not under_work:
        raise SystemExit(
            "task projects inside the auto-gpu-kernel checkout must live under work/"
        )
    if project.exists() and any(project.iterdir()) and not force:
        raise SystemExit(f"{project} exists and is not empty (use --force)")

    spec_text = Path(taskspec).read_text()
    raw = tomllib.loads(spec_text)
    cfg = _load_task(project, raw)  # validate before touching disk
    if "agent" in raw:
        # The brief already chooses; the CLI flags are defaults, not overrides.
        agent = raw["agent"].get("kind", agent)
    else:
        spec_text = spec_text.rstrip() + "\n" + agent_config_toml(agent, extensions)
    project.mkdir(parents=True, exist_ok=True)
    (project / "config.toml").write_text(spec_text)

    # --- clone (or copy) the target repo on its work branch ----------------
    work = cfg.work
    if cfg.repo_path:
        if not work.exists():
            _copy_local_repo(Path(taskspec).resolve().parent / cfg.repo_path, work)
        if cfg.branch:
            _run_git(["checkout", "-B", cfg.branch], work)
    elif not work.exists():
        print(f"  cloning {cfg.repo_url} -> {work}")
        subprocess.run(["git", "clone", cfg.repo_url, str(work)], check=True)
    if cfg.repo_url and cfg.branch:
        remote = subprocess.run(
            ["git", "ls-remote", "--heads", "origin", cfg.branch],
            cwd=work, capture_output=True, text=True, check=True,
        ).stdout.strip()
        if remote:
            _run_git(["checkout", cfg.branch], work)
        else:
            _run_git(["checkout", "-b", cfg.branch, f"origin/{cfg.base}"], work)
            push = subprocess.run(
                ["git", "push", "-u", "origin", cfg.branch],
                cwd=work, capture_output=True, text=True,
            )
            if push.returncode != 0:
                print(f"  warning: could not push work branch: {push.stderr.strip()}")

    _seed_experiments(
        project,
        "| Exp | Date | Description | Metric | Pass | Mode | Candidate | Harness | Notes |\n"
        "|---|---|---|---|---|---|---|---|---|\n",
    )

    # --- agent home --------------------------------------------------------
    origin = (
        "local snapshot, no remote — commit but never push"
        if cfg.repo_path
        else f"branch `{cfg.branch or cfg.base}`"
    )
    task_section = (
        "## The user's brief\n\n"
        f"**Task:** `{cfg.name}`\n\n"
        f"**Target repository:** `{cfg.workdir}/` ({origin})\n\n"
        f"**Hardware:** {cfg.gpus}x {cfg.gpu}, local\n\n"
        f"### Objective\n\n{cfg.objective}\n\n"
        f"### How to measure\n\n{cfg.measure}\n\n"
        f"### How to validate\n\n{cfg.validate}\n\n"
        f"### Hints\n\n{cfg.hints or 'None supplied.'}\n"
    )
    _agent_home(
        project,
        agent,
        (ASSETS / "task" / "bootstrap.md").read_text().rstrip()
        + "\n\n"
        + (ASSETS / "task" / "core.md").read_text().rstrip()
        + "\n\n"
        + task_section,
        ASSETS / "task",
    )

    # Project-level repo owns the generated harness and experiment history. The target
    # clone is ignored and manages its own commits independently.
    _git_init(project, ignore=f"{cfg.workdir}/\n")
    return project


def init(
    project: Path,
    definition_json: Path,
    language: str = "triton",
    backend: str = "modal",
    gpu: str = "B200",
    force: bool = False,
    agent: str = "omp",
    extensions: tuple[str, ...] = (),
) -> Path:
    if language not in languages():
        raise SystemExit(f"unknown language {language!r}; have: {', '.join(languages())}")
    if project.exists() and any(project.iterdir()) and not force:
        raise SystemExit(f"{project} exists and is not empty (use --force)")

    defn = json.loads(Path(definition_json).read_text())
    if "reference" not in defn:
        raise SystemExit(f"{definition_json} has no `reference` — not a usable definition")

    build_language, source_dir = BUILD.get(language, (language, language))
    kernel_file, baseline_file = "solution_fused.py", "solution_baseline.py"

    src = project / "solution" / source_dir
    src.mkdir(parents=True, exist_ok=True)
    _seed_experiments(
        project,
        "| Exp | Date | Description | Latency | Ref | Pass | Backend | Notes |\n"
        "|---|---|---|---|---|---|---|---|\n",
    )

    # AGENTS.md = generic core + language profile + generated kernel facts
    _agent_home(
        project,
        agent,
        (ASSETS / "core.md").read_text().rstrip()
        + "\n\n"
        + (ASSETS / "lang" / f"{language}.md").read_text().rstrip()
        + "\n\n"
        + _kernel_section(defn, source_dir, kernel_file, baseline_file),
        ASSETS,
    )

    (src / baseline_file).write_text(defn["reference"])
    (src / kernel_file).write_text(_stub(defn))

    (project / "config.toml").write_text(
        CONFIG.format(
            definition=defn["name"],
            language=build_language,
            lang_note=(
                f" — sources are `{language}`, which packs with the"
                f" {build_language} builder"
                if build_language != language
                else ""
            ),
            source_dir=source_dir,
            kernel_file=kernel_file,
            backend=backend,
            gpu=gpu,
        )
        + agent_config_toml(agent, extensions)
    )
    _git_init(project, ignore="results.json\n")
    return project
