"""The contract, two-sided:

1. Invariance, BITWISE. A row's output bytes do not depend on how the
   engine computed it. Per shape, every row of a 4096-row activation
   is computed (a) in one whole call and (b) in calls of M rows at
   offsets 0, 700 and 1025 for M in {1, 2, 3, 4, 17, 64, 65, 128,
   1536} — the engine's row counts and the wheel's class edges — and
   (c) the whole covered in 17-row and 64-row pieces. All equal to
   (a), bytes. There is no tolerance and none may be introduced.
2. Correctness, within bf16 rounding of the fp32 reference: on the
   whole and on the small arms the candidate's rel-L2 distance from
   `reference` is at most twice the wheel's own distance (+1e-6), the
   bound sparkle holds its M-invariant linear to. The wheel is the
   comparator, not the contract: its bytes are the thing being left.

Plus determinism over 8 calls, CUDA-graph capture and replay at M = 1
and 4 with x rewritten between replays, no torch matmul / compile on
the path, and loud rejection of bad operands.

Do not edit this file; a candidate that needs it changed is wrong.
"""

from __future__ import annotations

import pytest
import torch

from data import make_weight, make_x
from reference import reference, wheel
from shapes import ARM_MS, ARM_OFFSETS, SHAPES, VALIDATE_ROWS
from w4a16_gemm import w4a16_gemm

R = VALIDATE_ROWS


def _call(x, packed, scale):
  out = torch.empty(x.shape[0], packed.shape[0], dtype=torch.bfloat16,
                    device='cuda')
  w4a16_gemm(x.contiguous(), packed, scale, out)
  torch.cuda.synchronize()
  return out


def _assert_bitwise(out, ref, label):
  if torch.equal(out, ref):
    return
  diff = out != ref
  rows = torch.nonzero(diff.any(1)).flatten().tolist()
  raise AssertionError(
      f'{label}: {int(diff.sum())} elements differ in {len(rows)} rows '
      f'(first rows {rows[:8]}; max |delta| '
      f'{(out.float() - ref.float()).abs().max().item():.3e})')


def _assert_near_fp32(x, packed, scale, out, label):
  ref = reference(x, packed, scale).float()
  wh = wheel(x, packed, scale).float()
  rel = ((out.float() - ref).norm() / ref.norm()).item()
  rel_w = ((wh - ref).norm() / ref.norm()).item()
  assert rel <= 2.0 * rel_w + 1e-6, (
      f'{label}: rel-L2 vs fp32 {rel:.3e}, the wheel {rel_w:.3e}')


@pytest.fixture(scope='module', params=list(SHAPES))
def shape(request):
  return request.param


@pytest.fixture(scope='module')
def site(shape):
  n, k, _ = SHAPES[shape]
  packed, scale = make_weight(n, k, 11)
  x = make_x(R, k, 23)
  whole = _call(x, packed, scale)
  yield shape, x, packed, scale, whole
  del x, packed, scale, whole
  torch.cuda.empty_cache()


@pytest.mark.parametrize('m', ARM_MS)
def test_rows_at_m_equal_the_whole(site, m):
  shape, x, packed, scale, whole = site
  for off in ARM_OFFSETS:
    off = min(off, R - m)
    out = _call(x[off:off + m], packed, scale)
    _assert_bitwise(out, whole[off:off + m], f'{shape} M={m} at {off} vs whole')


@pytest.mark.parametrize('piece', [17, 64])
def test_whole_in_pieces(site, piece):
  shape, x, packed, scale, whole = site
  parts = [_call(x[i:i + piece], packed, scale) for i in range(0, R, piece)]
  _assert_bitwise(torch.cat(parts), whole, f'{shape} in {piece}-row pieces')


def test_within_bf16_rounding_of_fp32(site):
  shape, x, packed, scale, whole = site
  _assert_near_fp32(x, packed, scale, whole, f'{shape} whole')
  for m in (1, 4):
    out = _call(x[700:700 + m], packed, scale)
    _assert_near_fp32(x[700:700 + m], packed, scale, out, f'{shape} M={m}')


def test_deterministic_over_calls(site):
  shape, x, packed, scale, _ = site
  first = _call(x[:1025], packed, scale)
  for i in range(7):
    _assert_bitwise(_call(x[:1025], packed, scale), first,
                    f'{shape} call {i + 2} vs call 1')


@pytest.mark.parametrize('m', [1, 4])
def test_cuda_graph_capture_and_replay(site, m):
  """Decode and verify replay under CUDA graphs with x rewritten
  between replays: no host sync, no data-dependent host work."""
  shape, x, packed, scale, whole = site
  xb = x[:m].clone()
  out = torch.empty(m, packed.shape[0], dtype=torch.bfloat16, device='cuda')
  stream = torch.cuda.Stream()
  with torch.cuda.stream(stream):
    for _ in range(3):
      w4a16_gemm(xb, packed, scale, out)
  torch.cuda.current_stream().wait_stream(stream)
  graph = torch.cuda.CUDAGraph()
  with torch.cuda.graph(graph):
    w4a16_gemm(xb, packed, scale, out)
  out.zero_()
  graph.replay()
  torch.cuda.synchronize()
  _assert_bitwise(out, whole[:m], f'{shape} graph replay')
  xb.copy_(x[R - m:])
  graph.replay()
  torch.cuda.synchronize()
  _assert_bitwise(out, whole[R - m:], f'{shape} graph replay, rewritten x')


def test_no_torch_matmul_on_the_path(monkeypatch, site):
  import torch.nn.functional as F  # noqa: PLC0415
  shape, x, packed, scale, _ = site

  def boom(*a, **k):
    raise AssertionError('torch op on the main path')

  for mod, name in ((torch, 'matmul'), (torch, 'mm'), (torch, 'bmm'),
                    (torch, 'einsum'), (F, 'linear'), (torch, 'compile')):
    monkeypatch.setattr(mod, name, boom)
  _call(x[:4], packed, scale)


def test_rejects_bad_operands():
  n, k, _ = SHAPES['k_proj_global']
  packed, scale = make_weight(n, k, 1)
  x = make_x(4, k, 1)
  out = torch.empty(4, n, dtype=torch.bfloat16, device='cuda')
  with pytest.raises(ValueError):
    w4a16_gemm(x.float(), packed, scale, out)
  with pytest.raises(ValueError):
    w4a16_gemm(x, packed, scale[:, :1].contiguous(), out)
